server:
  port: 80
spring:
  thyemleaf:
   canche: false
  datasource:
driver-calass-name:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/memo_240319?characterEncoding=UTF-8
      username: root
      password: root
mybatis:
    mapper-locations: mappers/*Mapper.xml
